import secrets
import string

from django.db import transaction
from django.utils import timezone

from wifi.models import WiFiVoucher
from django.db import transaction
from django.utils import timezone
from wifi.models import WiFiSession, WiFiVoucher

def generate_voucher_code(length=8):
    """
    Generate a human-friendly Wi-Fi voucher code.
    """

    alphabet = (
        string.ascii_uppercase
        + string.digits
    )

    return "".join(
        secrets.choice(alphabet)
        for _ in range(length)
    )


def create_wifi_voucher(
    *,
    hotel,
    profile,
    valid_from,
    valid_until,
    max_devices=1,
    created_by=None,
    notes="",
):
    """
    Create a Wi-Fi voucher for a hotel.

    Business logic belongs here rather than in the view so that
    vouchers can later be generated by other workflows such as
    Front Desk, Conference management, APIs, or scheduled jobs.
    """

    if profile.hotel_id != hotel.id:
        raise ValueError(
            "Wi-Fi profile must belong to the selected hotel."
        )

    if valid_until <= valid_from:
        raise ValueError(
            "Voucher valid_until must be later than valid_from."
        )

    if max_devices < 1:
        raise ValueError(
            "Voucher must allow at least one device."
        )

    with transaction.atomic():

        while True:

            code = generate_voucher_code()

            if not WiFiVoucher.objects.filter(
                code=code
            ).exists():
                break

        voucher = WiFiVoucher.objects.create(
            hotel=hotel,
            code=code,
            profile=profile,
            valid_from=valid_from,
            valid_until=valid_until,
            status="ACTIVE",
            max_devices=max_devices,
            notes=notes,
            created_by=created_by,
        )

    return voucher

@transaction.atomic
def revoke_wifi_voucher(
    *,
    voucher,
    hotel,
):
    """
    Revoke a Wi-Fi voucher and terminate all active sessions
    associated with it.

    The voucher must belong to the supplied hotel.
    """

    if voucher.hotel_id != hotel.id:
        raise ValueError(
            "Wi-Fi voucher does not belong to the selected hotel."
        )

    if voucher.status == "REVOKED":
        return {
            "voucher": voucher,
            "sessions_terminated": 0,
        }

    now = timezone.now()

    # ---------------------------------------------------------
    # Revoke voucher
    # ---------------------------------------------------------

    voucher.status = "REVOKED"
    voucher.save(
        update_fields=["status"]
    )

    # ---------------------------------------------------------
    # Terminate active sessions
    # ---------------------------------------------------------

    active_sessions = WiFiSession.objects.filter(
        hotel=hotel,
        voucher=voucher,
        status="ACTIVE",
    )

    sessions_terminated = active_sessions.update(
        status="TERMINATED",
        ended_at=now,
    )

    return {
        "voucher": voucher,
        "sessions_terminated": sessions_terminated,
    }

