# Generated by Django 5.1.15 on 2026-01-15 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest',
        ),
        migrations.AlterField(
            model_name='folio',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.room'),
        ),
        migrations.RemoveField(
            model_name='guest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(help_text='Primary identifier', max_length=20, unique=True),
        ),
    ]
