# Generated by Django 5.1.15 on 2026-01-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_room_guest_alter_folio_room_and_more'),
        ('restaurant', '0007_alter_posorder_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
