# Generated by Django 5.1.15 on 2026-01-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folio',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='folio',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Guest associated with this stay', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='billing.guest'),
        ),
    ]
