# Generated by Django 5.1.15 on 2026-01-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_folio_guest_name_folio_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.guest'),
        ),
    ]
