# Generated by Django 5.1.15 on 2026-01-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_folio_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
