# Generated by Django 5.1.15 on 2026-01-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment_note_alter_payment_method_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(condition=models.Q(('folio_type', 'ROOM'), ('is_closed', False)), fields=('room',), name='one_active_room_folio'),
        ),
    ]
