# Generated by Django 5.1.15 on 2026-01-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_folio_one_active_room_folio'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folio',
            name='one_active_room_folio',
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(condition=models.Q(('folio_type', 'ROOM'), ('is_closed', False)), fields=('room',), name='unique_active_room_folio'),
        ),
    ]
