# Generated by Django 5.1.15 on 2026-01-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_folio_one_active_room_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='last_room_charge_date',
            field=models.DateField(blank=True, help_text='Last date room charge was applied', null=True),
        ),
    ]
