# Generated by Django 5.1.15 on 2026-01-27 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_folio_last_room_charge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='check_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='folio',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
