# Generated by Django 5.1.15 on 2026-02-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_folio_check_in_at_folio_check_out_at'),
        ('inventory', '0018_alter_department_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='inventory.hotel'),
            preserve_default=False,
        ),
    ]
