# Generated by Django 5.1.15 on 2026-03-04 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_folio_hotel'),
        ('inventory', '0018_alter_department_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='inventory.hotel'),
            preserve_default=False,
        ),
    ]
