# Generated by Django 5.1.15 on 2026-03-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_guest_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_number',
            field=models.CharField(blank=True, help_text='Passport / National ID', max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
