# Generated by Django 5.1.15 on 2026-03-15 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_guest_id_number_guest_nationality'),
        ('inventory', '0026_product_is_active'),
        ('rooms', '0008_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked In'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='RESERVED', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Walk-in, Phone, Website, Booking.com etc', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='billing.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.room')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomcategory')),
            ],
        ),
    ]
