# Generated by Django 5.1.15 on 2026-01-26 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive buildings cannot be used for new rooms'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
