# Generated by Django 5.1.15 on 2026-02-28 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_department_hotel'),
        ('rooms', '0004_room_hotel_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='inventory.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('hotel', 'name')},
        ),
    ]
