# Generated by Django 5.1.15 on 2026-03-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_options_alter_room_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('OCCUPIED_DIRTY', 'Occupied – Needs Cleaning'), ('VACANT_DIRTY', 'Vacant – Needs Cleaning'), ('OUT_OF_ORDER', 'Out of Order')], default='AVAILABLE', max_length=20),
        ),
    ]
