# Generated by Django 5.1.15 on 2026-08-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_hotelfeature_feature'),
        ('rooms', '0009_amenity_roomamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='inventory.hotel'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_hotel_amenity'),
        ),
    ]
