# Generated by Django 5.1.15 on 2026-08-19 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_hotelfeature_feature'),
        ('rooms', '0011_assign_amenities_to_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='inventory.hotel'),
        ),
    ]
