# Generated by Django 5.1.15 on 2026-09-01 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linen', '0010_linentransaction_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_clean_quantity', models.PositiveIntegerField(default=0)),
                ('declared_dirty_quantity', models.PositiveIntegerField(default=0)),
                ('received_clean_quantity', models.PositiveIntegerField(default=0)),
                ('received_dirty_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linen_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_receipts', to='linen.linenitem')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laundry_receipts_confirmed', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
