# Generated by Django 5.1.15 on 2026-09-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_reservation'),
        ('laundry', '0002_guestlaundryorder_guestlaundryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlaundryorder',
            name='billing_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_laundry_order', to='billing.charge'),
        ),
    ]
