# Generated by Django 5.1.15 on 2026-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_guestlaundryorder_billing_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlaundryorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='guestlaundryorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
