# Generated by Django 5.1.15 on 2026-09-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_lowstockrequest_fulfillment_type'),
        ('laundry', '0004_guestlaundryorder_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_services', to='inventory.hotel')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'name'), name='unique_laundry_service_name_per_hotel'), models.UniqueConstraint(fields=('hotel', 'code'), name='unique_laundry_service_code_per_hotel')],
            },
        ),
    ]
