# Generated by Django 5.1.15 on 2026-09-10 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_laundryservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlaundryitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laundry.laundryservice'),
        ),
    ]
