# Generated by Django 5.1.15 on 2026-09-13 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_stockmovementcostallocation'),
        ('laundry', '0006_guestlaundryitem_service'),
        ('linen', '0011_alter_linentransaction_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('HOTEL_LINEN', 'Hotel Linen'), ('GUEST_LAUNDRY', 'Guest Laundry')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laundry_processings', to='laundry.guestlaundryorder')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_processings', to='inventory.hotel')),
                ('linen_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laundry_processings', to='linen.linenitem')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_processings_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LaundryProcessingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_processing_material', to='inventory.stockmovement')),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='laundry.laundryprocessing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_processing_materials', to='inventory.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
