# Generated by Django 5.1.15 on 2026-09-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0007_laundryprocessing_laundryprocessingmaterial'),
        ('linen', '0011_alter_linentransaction_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryprocessing',
            name='linen_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laundry_processing', to='linen.linentransaction'),
        ),
    ]
