# Generated by Django 5.1.15 on 2026-08-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0032_alter_hotelfeature_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=17)),
                ('device_type', models.CharField(choices=[('COMPANY', 'Company Device'), ('GUEST', 'Guest Device'), ('OTHER', 'Other')], default='GUEST', max_length=20)),
                ('is_exempt', models.BooleanField(default=False, help_text='Exempt this device from guest Wi-Fi authentication.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_devices', to='inventory.hotel')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'mac_address'), name='unique_wifi_device_mac_per_hotel')],
            },
        ),
        migrations.CreateModel(
            name='WiFiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('download_speed_mbps', models.PositiveIntegerField(help_text='Maximum download speed in Mbps.')),
                ('upload_speed_mbps', models.PositiveIntegerField(help_text='Maximum upload speed in Mbps.')),
                ('max_devices', models.PositiveIntegerField(default=2, help_text='Maximum simultaneous devices allowed.')),
                ('session_timeout_minutes', models.PositiveIntegerField(blank=True, help_text='Optional maximum duration of a single session.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_profiles', to='inventory.hotel')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'name'), name='unique_wifi_profile_per_hotel')],
            },
        ),
    ]
