# Generated by Django 5.1.15 on 2026-08-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_reservation'),
        ('inventory', '0032_alter_hotelfeature_feature'),
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('max_devices', models.PositiveIntegerField(default=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_accounts', to='billing.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_accounts', to='inventory.hotel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radius_accounts', to='wifi.wifiprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'username'), name='unique_radius_username_per_hotel')],
            },
        ),
    ]
