# Generated by Django 5.1.15 on 2026-08-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_hotelfeature_feature'),
        ('wifi', '0004_wifisession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_usage', to='inventory.hotel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='wifi.wifisession')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
