# Generated by Django 5.1.15 on 2026-03-15 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='currency',
            field=models.CharField(default='₦', max_length=10),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
