# Generated by Django 5.1.15 on 2026-09-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_businessprofile_id'),
        ('inventory', '0047_stockmovementcostallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='inventory.hotel'),
        ),
    ]
