# Generated by Django 5.1.15 on 2026-09-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businessprofile_hotel'),
        ('inventory', '0047_stockmovementcostallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='inventory.hotel'),
        ),
    ]
