# Generated by Django 5.1.15 on 2026-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_businessprofile_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
