# Generated by Django 5.1.15 on 2026-08-31 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0045_lowstockrequest_fulfillment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_level', models.PositiveIntegerField(default=0, help_text='Target total quantity the hotel should maintain.')),
                ('minimum_level', models.PositiveIntegerField(default=0, help_text='Minimum total quantity before replenishment is required.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='linen_item', to='inventory.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
