# Generated by Django 5.1.15 on 2026-08-31 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('RECEIVED', 'Received'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('SENT_TO_LAUNDRY', 'Sent to Laundry'), ('RECEIVED_AT_LAUNDRY', 'Received at Laundry'), ('ISSUED_FROM_LAUNDRY', 'Issued from Laundry'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('WRITTEN_OFF', 'Written Off'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('from_location', models.CharField(blank=True, choices=[('STORE', 'Linen Store'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry')], max_length=20)),
                ('to_location', models.CharField(blank=True, choices=[('STORE', 'Linen Store'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linen_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='linen.linenitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linen_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
