# Generated by Django 5.1.15 on 2026-09-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0004_linenrequest'),
        ('rooms', '0012_alter_amenity_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLinenRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linen_requirements', to='rooms.roomcategory')),
                ('linen_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_category_requirements', to='linen.linenitem')),
            ],
            options={
                'ordering': ['category__name', 'linen_item__product__name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'linen_item'), name='unique_room_category_linen')],
            },
        ),
    ]
