# Generated by Django 5.1.15 on 2026-09-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0007_cleaningmaterialusage'),
        ('linen', '0005_roomlinenrequirement'),
        ('rooms', '0012_alter_amenity_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningLinenCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField()),
                ('found_quantity', models.PositiveIntegerField()),
                ('replaced_quantity', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linen_checks', to='housekeeping.cleaningassignment')),
                ('linen_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_checks', to='linen.linenitem')),
            ],
            options={
                'ordering': ['linen_item__product__name'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'linen_item'), name='unique_cleaning_assignment_linen_check')],
            },
        ),
        migrations.CreateModel(
            name='RoomLinenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linen_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_states', to='linen.linenitem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linen_states', to='rooms.room')),
            ],
            options={
                'ordering': ['room__room_number', 'linen_item__product__name'],
                'constraints': [models.UniqueConstraint(fields=('room', 'linen_item'), name='unique_room_linen_state')],
            },
        ),
    ]
