# Generated by Django 5.1.15 on 2026-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0006_cleaninglinencheck_roomlinenstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglinencheck',
            name='final_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
