# Generated by Django 5.1.15 on 2026-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0007_cleaninglinencheck_final_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaninglinencheck',
            old_name='replaced_quantity',
            new_name='clean_issued_quantity',
        ),
        migrations.AddField(
            model_name='cleaninglinencheck',
            name='dirty_collected_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
