# Generated by Django 5.1.15 on 2026-09-01 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0008_rename_replaced_quantity_cleaninglinencheck_clean_issued_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinenCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_quantity', models.PositiveIntegerField(default=0)),
                ('dirty_quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linen_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodies', to='linen.linenitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linen_custodies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'linen_item__product__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'linen_item'), name='unique_user_linen_custody')],
            },
        ),
    ]
