# Generated by Django 5.1.15 on 2026-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0009_linencustody'),
    ]

    operations = [
        migrations.AddField(
            model_name='linentransaction',
            name='condition',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty')], default='CLEAN', max_length=10),
        ),
    ]
