# Generated by Django 5.1.15 on 2026-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linen', '0010_linentransaction_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linentransaction',
            name='event_type',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('SENT_TO_LAUNDRY', 'Sent to Laundry'), ('RECEIVED_AT_LAUNDRY', 'Received at Laundry'), ('PROCESSED', 'Processed'), ('ISSUED_FROM_LAUNDRY', 'Issued from Laundry'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('WRITTEN_OFF', 'Written Off'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
    ]
