# Generated by Django 5.1.15 on 2026-01-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department'),
        ('inventory', '0003_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Required for operational staff (restaurant, store, kitchen, housekeeping, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('FRONTDESK', 'Front Desk / Reception'), ('RESTAURANT', 'Restaurant Staff'), ('STORE', 'Store Manager'), ('KITCHEN', 'Kitchen Staff'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry Staff'), ('GYM', 'Gym Staff'), ('ACCOUNTANT', 'Accountant')], default='FRONTDESK', max_length=20),
        ),
    ]
