# Generated by Django 5.1.15 on 2026-03-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('FRONTDESK', 'Front Desk / Reception'), ('RESTAURANT', 'Restaurant Staff'), ('STORE', 'Store Manager'), ('KITCHEN', 'Kitchen Staff'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry Staff'), ('GYM', 'Gym Staff'), ('ACCOUNTANT', 'Accountant')], default='FRONTDESK', max_length=20),
        ),
    ]
