# Generated by Django 5.1.15 on 2026-03-01 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('inventory', '0018_alter_department_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel user belongs to (Managers, Accountants)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.hotel'),
        ),
    ]
