# Generated by Django 5.1.15 on 2026-03-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, help_text='Head of department responsible for assignments and supervision'),
        ),
    ]
