# Generated by Django 5.1.15 on 2026-08-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_department_head'),
        ('inventory', '0033_organization_hotel_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_hotels',
            field=models.ManyToManyField(blank=True, help_text='Hotels assigned to General Managers.', related_name='assigned_managers', to='inventory.hotel'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventory.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department assigned to operational staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel assigned to this user when the role is hotel-specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventory.hotel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, help_text='Head of department responsible for assignments and supervision.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('GENERAL_MANAGER', 'General Manager'), ('MANAGER', 'Manager'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('ACCOUNTANT', 'Hotel Accountant'), ('FRONTDESK', 'Front Desk / Reception'), ('RESTAURANT', 'Restaurant Staff'), ('STORE', 'Store Manager'), ('KITCHEN', 'Kitchen Staff'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry Staff'), ('GYM', 'Gym Staff')], default='FRONTDESK', max_length=30),
        ),
    ]
