# Generated by Django 5.1.15 on 2026-01-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
