# Generated by Django 5.1.15 on 2026-01-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_reorder_level_alter_stock_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(default=1, help_text='Smallest unit used in stock (pcs, kg, litre)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Item'), ('SERVICE', 'Service')], default='RAW', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_unit',
            field=models.CharField(blank=True, help_text='Unit used when buying (carton, bag, crate)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='How many base units in one purchase unit'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
