# Generated by Django 5.1.15 on 2026-01-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_lowstockrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_received',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity in purchase unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
