# Generated by Django 5.1.15 on 2026-01-29 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_purchaseitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockrequest',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='inventory.purchaseorder'),
        ),
    ]
