# Generated by Django 5.1.15 on 2026-01-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchaseorder_paid_at_purchaseorder_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
