# Generated by Django 5.1.15 on 2026-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_base_unit_alter_product_purchase_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supply_source',
            field=models.CharField(choices=[('STORE', 'From Store'), ('DIRECT', 'Direct Purchase')], default='STORE', max_length=10),
        ),
    ]
