# Generated by Django 5.1.15 on 2026-02-13 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_supply_source'),
        ('kitchen', '0012_alter_directpurchase_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='ingredient_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='kitchen.ingredientrestockitem'),
        ),
    ]
