# Generated by Django 5.1.15 on 2026-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stocktransfer_ingredient_request_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowstockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
