# Generated by Django 5.1.15 on 2026-02-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_lowstockrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('KITCHEN', 'Kitchen'), ('STORE', 'Store'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry'), ('GYM', 'Gym'), ('FRONTDESK', 'Front Desk'), ('OTHER', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
