# Generated by Django 5.1.15 on 2026-02-28 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_department_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('STORE', 'Store'), ('RESTAURANT', 'Restaurant'), ('FRONTDESK', 'Front Desk'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry'), ('GYM', 'Gym')], max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='inventory.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hotel', 'name')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
    ]
