# Generated by Django 5.1.15 on 2026-02-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_hotel_alter_department_department_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='inventory.hotel'),
            preserve_default=False,
        ),
    ]
