# Generated by Django 5.1.15 on 2026-03-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_hotel_created_at_hotel_slug_alter_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
