# Generated by Django 5.1.15 on 2026-03-07 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_department_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(help_text='Unit used internally (kg, pcs, litre)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_unit',
            field=models.CharField(blank=True, help_text='Unit used when buying (bag, carton, crate)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, help_text='Minimum quantity before reorder alert'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='How many base units are in purchase unit'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_product_name'),
        ),
    ]
