# Generated by Django 5.1.15 on 2026-03-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_supplier_options_supplier_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('KITCHEN', 'Kitchen'), ('STORE', 'Store'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry'), ('GYM', 'Gym'), ('POOL', 'Swimming Pool'), ('SPA', 'Spa'), ('BOUTIQUE', 'Boutique Shop')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments allowed to stock this product', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(help_text='Internal unit (kg, pcs, litre)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_unit',
            field=models.CharField(blank=True, help_text='Purchase unit (bag, carton, crate)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='How many base units in purchase unit'),
        ),
        migrations.AddField(
            model_name='hotelfeature',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='inventory.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelfeature',
            unique_together={('hotel', 'feature')},
        ),
    ]
