# Generated by Django 5.1.15 on 2026-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_hotelfeature_remove_product_unique_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('FOOD', 'Prepared Food'), ('DRINK', 'Beverage'), ('HOUSEKEEPING', 'Housekeeping Supply'), ('LAUNDRY', 'Laundry Supply'), ('BOUTIQUE', 'Boutique Item'), ('SERVICE', 'Service')], default='RAW', max_length=20),
        ),
    ]
