# Generated by Django 5.1.15 on 2026-03-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_type',
            field=models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('RESALE', 'Resale Item'), ('INTERNAL', 'Internal Use'), ('ASSET', 'Asset')], default='CONSUMABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments allowed to use/request this product', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
