# Generated by Django 5.1.15 on 2026-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per purchase unit (carton, bag, crate)', max_digits=12),
        ),
    ]
