# Generated by Django 5.1.15 on 2026-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_product_purchase_cost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('FRONTDESK', 'Front Desk'), ('HOUSEKEEPING', 'Housekeeping'), ('RESTAURANT', 'Restaurant'), ('KITCHEN', 'Kitchen'), ('STORE', 'Store'), ('LAUNDRY', 'Laundry'), ('GYM', 'Gym'), ('ACCOUNTING', 'Accounting'), ('ADMINISTRATION', 'Administration'), ('HUMAN_RESOURCES', 'Human Resources'), ('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('IT', 'Information Technology')], max_length=30),
        ),
    ]
