# Generated by Django 5.1.15 on 2026-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_department_unique_together_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfeature',
            name='feature',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('KITCHEN', 'Kitchen'), ('STORE', 'Store'), ('HOUSEKEEPING', 'Housekeeping'), ('LAUNDRY', 'Laundry'), ('GYM', 'Gym'), ('POOL', 'Swimming Pool'), ('SPA', 'Spa'), ('BOUTIQUE', 'Boutique Shop'), ('WIFI', 'Wi-Fi Management')], max_length=30),
        ),
    ]
