# Generated by Django 5.1.15 on 2026-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_department_id_alter_hotel_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['hotel__name', 'name']},
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='unique_department_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_department_name_per_hotel'),
        ),
    ]
