# Generated by Django 5.1.15 on 2026-08-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_purchaseorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='inventory.hotel'),
        ),
    ]
