# Generated by Django 5.1.15 on 2026-08-27 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_supplier_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='inventory.hotel'),
        ),
    ]
