# Generated by Django 5.1.15 on 2026-08-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_stockmovement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='stock_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='inventory.lowstockrequest'),
        ),
    ]
