# Generated by Django 5.1.15 on 2026-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_stocktransfer_stock_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowstockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
