# Generated by Django 5.1.15 on 2026-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_alter_lowstockrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockrequest',
            name='fulfillment_type',
            field=models.CharField(choices=[('STORE', 'From Store'), ('PURCHASE', 'Purchase')], default='STORE', max_length=10),
        ),
    ]
