# Generated by Django 5.1.15 on 2026-09-12 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_lowstockrequest_fulfillment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per product base unit.', max_digits=12)),
                ('is_opening_balance', models.BooleanField(default=False, help_text='True when this layer represents stock that existed before cost-layer tracking.')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_cost_layers', to='inventory.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.product')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.purchaseitem')),
            ],
            options={
                'ordering': ['received_at', 'id'],
                'indexes': [models.Index(fields=['product', 'department', 'quantity_remaining', 'received_at'], name='inventory_s_product_9bc39a_idx')],
            },
        ),
    ]
