# Generated by Django 5.1.15 on 2026-09-13 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_stockcostlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_allocations', to='inventory.stockcostlayer')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
