# Generated by Django 5.1.15 on 2026-03-14 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0007_alter_room_options_alter_room_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('cleaned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_logs', to='rooms.room')),
            ],
        ),
    ]
