# Generated by Django 5.1.15 on 2026-03-14 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0002_cleaningassignment'),
        ('rooms', '0007_alter_room_options_alter_room_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('found_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('FOUND', 'Found'), ('CLAIMED', 'Claimed'), ('DISPOSED', 'Disposed')], default='FOUND', max_length=20)),
                ('claimed_by', models.CharField(blank=True, max_length=200)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('found_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_items', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
            ],
        ),
    ]
