# Generated by Django 5.1.15 on 2026-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0003_lostfounditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cleaningassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('INSPECTION', 'Waiting Inspection')], default='ASSIGNED', max_length=20),
        ),
    ]
