# Generated by Django 5.1.15 on 2026-08-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0005_cleaningassignment_inspected_at_and_more'),
        ('inventory', '0035_alter_department_options_and_more'),
        ('rooms', '0012_alter_amenity_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lost_found_items', to='inventory.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='rooms.room'),
        ),
    ]
