# Generated by Django 5.1.15 on 2026-08-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenanceworknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='completion_outcome',
            field=models.CharField(blank=True, choices=[('ROOM_READY', 'Room Ready'), ('HOUSEKEEPING_REQUIRED', 'Housekeeping Required'), ('NOT_APPLICABLE', 'Room Not Affected')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
