# Generated by Django 5.1.15 on 2026-08-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenanceticket_completion_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='room_status_before_maintenance',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('OCCUPIED_DIRTY', 'Occupied – Needs Cleaning'), ('VACANT_DIRTY', 'Vacant – Needs Cleaning'), ('OUT_OF_ORDER', 'Out of Order')], max_length=20, null=True),
        ),
    ]
