# Generated by Django 5.1.15 on 2026-08-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenanceasset_maintenanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenanceschedule'),
        ),
    ]
