# Generated by Django 5.1.15 on 2026-01-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='charge_to_room',
            field=models.BooleanField(default=False, help_text='If checked, charge goes to room folio'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.folio'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='take_payment_now',
            field=models.BooleanField(default=True, help_text='If unchecked, payment happens at checkout'),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CHARGED', 'Charged'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
