# Generated by Django 5.1.15 on 2026-01-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('restaurant', '0002_posorder_charge_to_room_posorder_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Required if charging to room', null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.room'),
        ),
    ]
