# Generated by Django 5.1.15 on 2026-01-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('restaurant', '0003_posorder_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='take_payment_now',
        ),
        migrations.AlterField(
            model_name='posorder',
            name='charge_to_room',
            field=models.BooleanField(default=False, help_text='If checked, order is charged to room folio'),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='folio',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.folio'),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Select when charging to room', null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.room'),
        ),
    ]
