# Generated by Django 5.1.15 on 2026-01-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_posorder_take_payment_now_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('DRINK', 'Drink'), ('FOOD', 'Food')], default='DRINK', max_length=10),
        ),
    ]
