# Generated by Django 5.1.15 on 2026-01-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_posorder_is_refunded_posorder_refund_reason_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Select when charging to room', null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.room'),
        ),
    ]
