# Generated by Django 5.1.15 on 2026-01-27 23:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_folio_check_in_at_folio_check_out_at'),
        ('restaurant', '0007_alter_posorder_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='charge_to_room',
        ),
        migrations.RemoveField(
            model_name='posorder',
            name='room',
        ),
        # migrations.AlterField(
        #     model_name='posorder',
        #     name='folio',
        #     field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='billing.folio'),
        #     preserve_default=False,
        # ),
    ]
