# Generated by Django 5.1.15 on 2026-01-27 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_folio_check_in_at_folio_check_out_at'),
        ('restaurant', '0008_remove_posorder_charge_to_room_remove_posorder_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='billing.folio'),
        ),
    ]
