# Generated by Django 5.1.15 on 2026-03-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-opened_at']},
        ),
    ]
