# Generated by Django 5.1.15 on 2026-03-13 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_shift_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.shift'),
        ),
    ]
