# Generated by Django 5.1.15 on 2026-03-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_restauranttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.restauranttable'),
        ),
    ]
