# Generated by Django 5.1.15 on 2026-03-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_posorder_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='status',
        ),
    ]
