# Generated by Django 5.1.15 on 2026-03-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_product_usage_type_alter_product_departments_and_more'),
        ('restaurant', '0015_remove_restauranttable_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_menu_item_per_product'),
        ),
    ]
