# Generated by Django 5.1.15 on 2026-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_menuitem_unique_menu_item_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
