# Generated by Django 5.1.15 on 2026-03-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_businessday'),
        ('restaurant', '0017_posorder_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='business_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.businessday'),
        ),
    ]
