# Generated by Django 5.1.15 on 2026-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_posorder_business_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='is_cogs_posted',
            field=models.BooleanField(default=False),
        ),
    ]
