# Generated by Django 5.1.15 on 2026-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_posorder_is_cogs_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
