# Generated by Django 5.1.15 on 2026-01-31 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_base_unit_alter_product_purchase_unit_and_more'),
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionIngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, help_text='Quantity expected based on recipe', max_digits=10)),
                ('actual_quantity', models.DecimalField(decimal_places=3, help_text='Quantity actually used by kitchen', max_digits=10)),
                ('variance', models.DecimalField(decimal_places=3, help_text='actual - expected', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_usages', to='kitchen.productionbatch')),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
    ]
