# Generated by Django 5.1.15 on 2026-02-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_base_unit_alter_product_purchase_unit_and_more'),
        ('kitchen', '0002_productioningredientusage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_per_recipe'),
        ),
    ]
