# Generated by Django 5.1.15 on 2026-02-02 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_supply_source'),
        ('kitchen', '0004_ingredientrestockrequest_ingredientrestockitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrestockrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredientrestockitem',
            name='routed_to',
        ),
        migrations.RemoveField(
            model_name='ingredientrestockitem',
            name='status',
        ),
        migrations.AddField(
            model_name='ingredientrestockitem',
            name='route',
            field=models.CharField(choices=[('STORE', 'From Store'), ('DIRECT', 'Direct Purchase')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientrestockrequest',
            name='kitchen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_requests', to='inventory.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientrestockitem',
            name='ingredient',
            field=models.ForeignKey(limit_choices_to={'product_type': 'RAW'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='ingredientrestockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
