# Generated by Django 5.1.15 on 2026-02-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_rename_requested_at_ingredientrestockrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrestockitem',
            old_name='route',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='ingredientrestockrequest',
            name='kitchen',
        ),
        migrations.AlterField(
            model_name='ingredientrestockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
