# Generated by Django 5.1.15 on 2026-02-05 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_ingredientrestockrequest_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, help_text='Market/vendor name', max_length=150)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PURCHASED', 'Purchased'), ('RECEIVED', 'Received')], default='APPROVED', max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_direct_purchases', to=settings.AUTH_USER_MODEL)),
                ('ingredient_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase', to='kitchen.ingredientrestockrequest')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
