# Generated by Django 5.1.15 on 2026-02-05 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_supply_source'),
        ('kitchen', '0008_directpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direct_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.directpurchase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
