# Generated by Django 5.1.15 on 2026-02-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_supply_source'),
        ('kitchen', '0009_directpurchaseitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='directpurchase',
            old_name='purchased_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='directpurchaseitem',
            old_name='direct_purchase',
            new_name='purchase',
        ),
        migrations.RemoveField(
            model_name='directpurchase',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='directpurchase',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='directpurchase',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='ingredient_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directpurchase', to='kitchen.ingredientrestockrequest'),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='directpurchaseitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'RAW'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
