# Generated by Django 5.1.15 on 2026-02-08 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_supply_source'),
        ('kitchen', '0010_rename_purchased_at_directpurchase_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directpurchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directpurchase',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_direct_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directpurchase',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='ingredient_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase', to='kitchen.ingredientrestockrequest'),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PAID', 'Paid'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
