# Generated by Django 5.1.15 on 2026-02-11 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_supply_source'),
        ('kitchen', '0011_directpurchase_paid_at_directpurchase_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpurchase',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='ingredientrestockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Received')], default='PENDING', max_length=20),
        ),
    ]
