# Generated by Django 5.1.15 on 2026-02-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0012_alter_directpurchase_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrestockrequest',
            name='purchase_order',
        ),
    ]
