# Generated by Django 5.1.15 on 2026-02-24 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_lowstockrequest_status'),
        ('kitchen', '0013_remove_ingredientrestockrequest_purchase_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeitem',
            name='unique_ingredient_per_recipe',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='control_mode',
            field=models.CharField(choices=[('STRICT', 'Strict (No Variance)'), ('TOLERANCE', 'Tolerance Allowed'), ('FLEXIBLE', 'Fully Flexible')], default='STRICT', max_length=15),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='tolerance_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allowed variance % (only for TOLERANCE mode)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(limit_choices_to={'product_type': 'RAW'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
