# Generated by Django 5.1.15 on 2026-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_journalentry_business_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SALE', 'Sale'), ('COGS', 'COGS'), ('PURCHASE', 'Purchase'), ('CLOSING', 'Closing')], default='NORMAL', max_length=20),
        ),
    ]
