# Generated by Django 5.1.15 on 2026-03-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_journalentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SALE', 'Sale'), ('COGS', 'COGS'), ('PURCHASE', 'Purchase'), ('CLOSING', 'Closing'), ('PRODUCTION', 'Production')], default='NORMAL', max_length=20),
        ),
    ]
