# Generated by Django 5.1.15 on 2026-04-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentry_entry_type'),
        ('inventory', '0030_product_purchase_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('hotel', 'reference', 'entry_type')},
        ),
    ]
