# Generated by Django 5.1.15 on 2026-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_manual_entries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='allow_posting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='system_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('current_asset', 'Current Asset'), ('inventory', 'Inventory'), ('fixed_asset', 'Fixed Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long-Term Liability'), ('equity', 'Equity'), ('income', 'Income'), ('other_income', 'Other Income'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense'), ('other_expense', 'Other Expense')], max_length=20),
        ),
    ]
