# Generated by Django 5.1.15 on 2026-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_account_allow_manual_entries_account_allow_posting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
