# Generated by Django 5.1.15 on 2026-08-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='opening_balance',
        ),
    ]
