# Generated by Django 5.1.15 on 2026-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_bankaccount_opening_balance'),
        ('inventory', '0031_alter_department_unique_together_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('hotel', 'slug'), name='unique_account_slug_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='unique_account_code_per_hotel'),
        ),
    ]
